/**
 * SUPERVOLCANO DATABASE SCHEMA
 *
 * This file defines the core data model for the platform.
 *
 * Key Concepts:
 * - Organizations: Either OEM partners OR individual property owners
 * - Locations: Either test environments (owned by SuperVolcano) OR properties (owned by customers)
 * - Users: Have roles that determine what they can see and do
 * - Location Assignments: Grant organizations access to specific locations
 *
 * Last updated: 2025-01-26
 */

// ============================================================================
// USER ROLES
// ============================================================================

/**
 * User roles in the system.
 *
 * @role admin - SuperVolcano internal team
 *   - Creates test locations for OEM partners
 *   - Assigns locations to partner organizations
 *   - Platform-wide analytics and management
 *   - Web app only
 *
 * @role partner_manager - OEM partner employee (e.g., Figure AI manager)
 *   - Views locations ASSIGNED by SuperVolcano (cannot create)
 *   - Manages their organization's teleoperators
 *   - Views performance analytics for their team
 *   - Web + Mobile
 *
 * @role location_owner - Individual property owner/manager
 *   - CREATES and manages their own properties
 *   - Builds property structure (floors, rooms, tasks)
 *   - Manages their cleaners
 *   - Views cleaning analytics
 *   - Web + Mobile
 *
 * @role oem_teleoperator - OEM worker (operates robots remotely)
 *   - Works for OEM partners
 *   - Views assigned test locations only
 *   - Records videos and completes tasks
 *   - Mobile only
 *
 * @role location_cleaner - Cleaning worker (performs cleaning)
 *   - Works for property owners
 *   - Views assigned properties only
 *   - Records videos and completes cleaning tasks
 *   - Mobile only
 */
// Canonical UserRole lives in the user domain; re-exported here so existing
// `@/types/database` importers keep working without a second definition to drift.
import type { UserRole } from "@/domain/user/user.types";
export type { UserRole };

/**
 * User entity
 *
 * Firestore collection: users
 * Document ID: Auto-generated by Firebase Auth
 */
export interface User {
  id: string;
  email: string;
  name: string;

  /**
   * User's role determines their permissions.
   * See UserRole type documentation for details.
   */
  role: UserRole;

  /**
   * Organization the user belongs to.
   * - NULL for admins (they're SuperVolcano employees)
   * - Set for all other roles
   */
  organization_id: string | null;

  // Metadata
  created_at: string; // ISO 8601
  updated_at: string; // ISO 8601

  // Optional profile fields
  phone?: string;
  avatar_url?: string;

  // User preferences
  notifications_enabled: boolean;
}

// ============================================================================
// ORGANIZATIONS
// ============================================================================

/**
 * Organization types determine business model and permissions.
 *
 * @type partner - OEM robotics company (e.g., Figure AI, Tesla Bot)
 *   - Gets locations ASSIGNED by SuperVolcano
 *   - Cannot create locations (SuperVolcano curates test environments)
 *   - Pays for access to test locations
 *
 * @type location_owner - Individual property owner/manager
 *   - CREATES their own locations (properties)
 *   - Full control over their properties
 *   - Pays for property management software
 */
// NOTE: this DIVERGES from `@/types/organization.types` OrganizationType
// (which is 'supervolcano' | 'oem_partner' | 'location_owner'). Not unified
// here on purpose — reconciling the two org-type models needs product input.
// Treat `@/types/organization.types` as the richer/canonical version.
export type OrganizationType = "partner" | "location_owner";

/**
 * Organization entity
 *
 * Firestore collection: organizations
 * Document ID: Auto-generated
 *
 * Represents either:
 * - An OEM partner company (type: 'partner')
 * - An individual property owner's "organization" (type: 'location_owner')
 */
export interface Organization {
  id: string;
  name: string;

  /**
   * Type determines what this organization can do.
   * - partner: Gets locations assigned, can't create
   * - location_owner: Creates their own locations
   */
  type: OrganizationType;

  /**
   * User who created this organization.
   * - For partners: SuperVolcano admin
   * - For property owners: The property owner themselves
   */
  created_by: string; // User ID

  // Metadata
  created_at: string;
  updated_at: string;

  // Settings
  settings: {
    /**
     * Whether to auto-generate tasks from location structure.
     * If true, tasks are created automatically when rooms/targets are added.
     */
    auto_generate_tasks: boolean;

    /**
     * Whether videos require approval before being marked as complete.
     */
    require_video_approval: boolean;
  };
}

// ============================================================================
// LOCATIONS
// ============================================================================

/**
 * Location entity
 *
 * Firestore collection: locations
 * Document ID: Auto-generated
 *
 * Represents a physical location where work is performed.
 * Can be either:
 * - Test environment (owned by SuperVolcano, assigned to partners)
 * - Customer property (owned by property owner)
 */
export interface Location {
  id: string;
  name: string;
  address: string;

  /**
   * Organization this location belongs to.
   * - For test environments: Partner organization it's assigned to
   * - For properties: Property owner's organization
   */
  organization_id: string;

  /**
   * User who created this location.
   * - For test environments: SuperVolcano admin
   * - For properties: Property owner
   */
  created_by: string; // User ID

  /**
   * User who owns this location.
   * - For test environments: NULL (SuperVolcano owns it)
   * - For properties: Property owner's user ID
   */
  owned_by: string | null; // User ID or null

  /**
   * Whether this is a test environment or customer property.
   * Derived from owned_by:
   * - owned_by === null → test environment
   * - owned_by !== null → customer property
   */
  is_test_environment: boolean;

  // Metadata
  created_at: string;
  updated_at: string;
}

// ============================================================================
// LOCATION ASSIGNMENTS
// ============================================================================

/**
 * Location Assignment entity
 *
 * Firestore collection: location_assignments
 * Document ID: Auto-generated
 *
 * Grants an organization access to a specific location.
 *
 * Use cases:
 * 1. SuperVolcano assigns test location to OEM partner
 * 2. Property owner "assigns" their property to themselves (implicit)
 *
 * Query patterns:
 * - Get all locations for an organization: WHERE organization_id == X
 * - Get all organizations with access to location: WHERE location_id == X
 */
export interface LocationAssignment {
  id: string;

  /**
   * Organization being granted access
   */
  organization_id: string;

  /**
   * Location being accessed
   */
  location_id: string;

  /**
   * User who made this assignment
   * - For test environments: SuperVolcano admin
   * - For properties: Auto-assigned (system)
   */
  assigned_by: string; // User ID

  /**
   * When this assignment was created
   */
  assigned_at: string; // ISO 8601
}

// ============================================================================
// USER-LOCATION ASSIGNMENTS (Field Operators)
// ============================================================================

/**
 * User Location Assignment entity
 *
 * Firestore collection: user_location_assignments
 * Document ID: Auto-generated
 *
 * Assigns a specific field operator to work at a specific location.
 *
 * Workflow:
 * 1. Manager (partner_manager or location_owner) invites field worker
 * 2. Field operator accepts invite
 * 3. User-location assignment is created
 * 4. Field operator can now see and work at this location
 */
export interface UserLocationAssignment {
  id: string;

  /**
   * Field operator being assigned
   */
  user_id: string;

  /**
   * Location they're assigned to
   */
  location_id: string;

  /**
   * Organization context (for scoping)
   */
  organization_id: string;

  /**
   * Manager who assigned this worker
   */
  assigned_by: string; // User ID

  /**
   * When assignment was created
   */
  assigned_at: string; // ISO 8601
}

// ============================================================================
// INVITE CODES
// ============================================================================

/**
 * Invite Code entity
 *
 * Firestore collection: invite_codes
 * Document ID: Auto-generated
 *
 * Used by managers to invite field operators to their organization.
 *
 * Workflow:
 * 1. Manager generates invite code
 * 2. Manager shares code with field operator (out of band)
 * 3. Field operator enters code in app
 * 4. System validates code and assigns operator to organization
 */
export interface InviteCode {
  id: string;

  /**
   * The actual code (e.g., "ABC123")
   * - 6 characters
   * - Uppercase alphanumeric
   * - Unique across all active codes
   */
  code: string;

  /**
   * Organization this code grants access to
   */
  organization_id: string;

  /**
   * Manager who created this code
   */
  created_by: string; // User ID

  /**
   * When code was created
   */
  created_at: string;

  /**
   * When code expires (optional)
   * NULL = never expires
   */
  expires_at: string | null;

  /**
   * Maximum number of times this code can be used
   * Typical values:
   * - 1 = single use
   * - 999999 = unlimited
   */
  max_uses: number;

  /**
   * How many times code has been used
   */
  current_uses: number;

  /**
   * Whether code is still usable
   * Set to false when:
   * - current_uses >= max_uses
   * - Manually deactivated by creator
   * - Expired (expires_at < now)
   */
  active: boolean;
}

// ============================================================================
// FLOORS, ROOMS, TARGETS, ACTIONS (Hierarchy)
// ============================================================================

/**
 * These entities define the structure of a location.
 * Hierarchy: Location → Floor → Room → Target → Action
 *
 * This structure is identical whether the location is:
 * - A test environment (for robot testing)
 * - A property (for cleaning)
 *
 * The same data model serves both business models.
 */

export interface Floor {
  id: string;
  location_id: string;
  name: string; // "Floor 1", "Ground Floor", etc.
  floor_number: number;
  created_at: string;
  updated_at: string;
}

export interface Room {
  id: string;
  floor_id: string;
  location_id: string; // Denormalized for easier querying
  name: string; // "Kitchen", "Bedroom", "Office", etc.
  room_type: string; // 'kitchen', 'bathroom', 'bedroom', etc.
  created_at: string;
  updated_at: string;
}

export interface Target {
  id: string;
  room_id: string;
  floor_id: string; // Denormalized
  location_id: string; // Denormalized
  name: string; // "Counter", "Sink", "Desk", etc.
  target_type: string;
  created_at: string;
  updated_at: string;
}

export interface Action {
  id: string;
  target_id: string;
  room_id: string; // Denormalized
  floor_id: string; // Denormalized
  location_id: string; // Denormalized
  organization_id: string; // For scoping
  name: string; // "Wipe", "Dust", "Sanitize", etc.
  description?: string;

  /**
   * Task status
   * - pending: Not started
   * - in_progress: Field operator is working on it
   * - completed: Video uploaded and task marked done
   * - skipped: Intentionally skipped
   */
  status: "pending" | "in_progress" | "completed" | "skipped";

  /**
   * Field operator assigned to this task (optional)
   */
  assigned_to?: string; // User ID

  /**
   * Video evidence of completion
   */
  video_url?: string;
  video_uploaded_at?: string;

  /**
   * Completion tracking
   */
  completed_at?: string;
  completed_by?: string; // User ID

  /**
   * Estimated time to complete (minutes)
   */
  estimated_time?: number;

  created_at: string;
  updated_at: string;
}
